### ISSUE TITLE
Sidebar closing when clicking inside it

### ISSUE THREAD

**Issue by RomkaLTU** [mbj36/vue-burger-menu#56] opened 2019-04-10 13:41 UTC
It's happening when you click something inside the sidebar, for example trying to clikc on text input ant type something. Text input is inside slot. 

```
<Slide right>
  <div><input type="text"></div>
</Slide>
```

**Comment by jesperholstjh** [comment] 2019-10-15 12:38
Have a look at https://github.com/mbj36/vue-burger-menu/issues/30. The issue is fixed but @mbj36 hasn't merged it to master. We are also waiting for this.

**Comment by mbj36** [comment] 2019-10-15 13:27
It's merged @jesperholstjh

**Comment by toyoshima-c-fixer** [comment] 2019-10-28 03:41
@mbj36 
Has it been modified? Looks like it still closes when clicking inside.

**Comment by Brice187** [comment] 2019-11-18 15:45
Found the issue in vue-burger-menu.common.js:
```
if (element && element !== target && !element.contains(target) && e.target.className !== 'bm-menu' && this.isSideBarOpen && !this.disableOutsideClick) {
    this.closeMenu();
}
```
The condition e.target.className !== 'bm-menu'  only checks the class of the top level elements. if these have child elements that do not have "bm-menu", the click is considered "outside"

**Comment by gavinhewitt** [comment] 2019-12-05 10:42
Having the same issue

**Comment by Brice187** [comment] 2019-12-05 10:44
i fixed it in my PR, have a look or wait for the maintainer to merge the PR ;)

**Closed** 2020-03-05 16:08 UTC
